"""empty message

Revision ID: 1d33c30625d
Revises: None
Create Date: 2017-03-11 19:27:10.360009

"""

# revision identifiers, used by Alembic.
revision = '1d33c30625d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
